In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50])
np.argmax(arr)

4

In [3]:
arr = np.array([1, 2, 3, 4, 5])

In [4]:
np.where(arr > 2)

(array([2, 3, 4], dtype=int64),)

In [5]:
arr = np.array([1, 2, 3, 4, 5])
result = np.diff(arr)
print(result)

[1 1 1 1]


In [6]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.dot(arr1, arr2)

32

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.mean(arr, axis=0)
print(result)


[2.5 3.5 4.5]
