In [2]:
import numpy as np
import pandas as pd

In [2]:
one=np.array([1,2,3,4,5,6])

In [3]:
one

array([1, 2, 3, 4, 5, 6])

In [4]:
type(one)

numpy.ndarray

In [7]:
one=np.array([[1,2,3],[4,5,6]])

In [8]:
one

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
one=np.ones((3,2))

In [10]:
one

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
range_array = np.arange(0, 10, 2)

In [12]:
range_array

array([0, 2, 4, 6, 8])

In [14]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d.shape)  # Shape of the array (rows, columns)
print(arr_2d.ndim)   # Number of dimensions
print(arr_2d.size)   # Total number of elements
print(arr_2d.dtype)  # Data type of the elements


(2, 3)
2
6
int32


In [15]:
# Create an array of values
data = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

# Calculate the standard deviation
std_dev = np.std(data)


In [16]:
std_dev

1.0

In [18]:
df=pd.read_csv('Students_data.csv')

In [19]:
df

StudentID     Name    Citizen Group  Score
0        101    Akash      India     A     85
1        105    Rohit      India     A     78
2        111    Gagan      India     B     92
3        122     Josh    England     A     88
4        125  Chandan      India     B     75
5        130   Ramesh    England     A     91
6        151    Starc  Australia     B     82
7        158  Krishna      India     A     89
8        160    Jugal      India     B     76
9        170  Anushka  Australia     A     90

In [24]:
mean_score = df['Score'].mean()

In [26]:
mean_score

84.6

In [27]:
std_score = df['Score'].std()

In [29]:
std_score

6.432556084308771

In [32]:
max = df['Score'].max()

In [33]:
max

92

In [37]:
my_sort=df.sort_values(by='Score', ascending=False)

In [38]:
my_sort.head(5)

StudentID     Name    Citizen Group  Score
2        111    Gagan      India     B     92
5        130   Ramesh    England     A     91
9        170  Anushka  Australia     A     90
7        158  Krishna      India     A     89
3        122     Josh    England     A     88

In [39]:
arr=np.arange(1,10)

In [40]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
myarr=arr*arr

In [43]:
myarr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [44]:
mean=myarr.mean()

In [45]:
std=myarr.std()

In [46]:
mean

31.666666666666668

In [47]:
std

26.474306202219704

In [49]:
np.square(arr)

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [52]:
myarr=arr**2 

In [53]:
myarr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [59]:
my_arr=np.array([[1,2,3],[8,9,7]])


In [60]:
my_arr


array([[1, 2, 3],
       [8, 9, 7]])

In [61]:
my_arr2=np.array([[3,4,5],[9,8,7]])

In [62]:
my_arr2

array([[3, 4, 5],
       [9, 8, 7]])

In [63]:
my_new_arr=my_arr*my_arr2

In [64]:
my_new_arr

array([[ 3,  8, 15],
       [72, 72, 49]])

In [67]:
my_arr = np.array([[1, 2], [3, 4]])
my_arr2 = np.array([[5, 6], [7, 8]])

In [68]:
my_new_arr = my_arr @ my_arr2

In [69]:
my_new_arr

array([[19, 22],
       [43, 50]])

In [70]:
my_new_arr=np.dot(my_arr,my_arr2)

In [71]:
my_new_arr

array([[19, 22],
       [43, 50]])

In [74]:
det=np.linalg.det(my_arr)

In [75]:
det

-2.0000000000000004

In [94]:
ran=np.random.rand(100)

In [95]:
ran

array([0.38214878, 0.60110287, 0.61475187, 0.38271634, 0.87209329,
       0.15752153, 0.5267614 , 0.40842652, 0.03176431, 0.26110332,
       0.57871003, 0.18725402, 0.09484897, 0.43438479, 0.82430921,
       0.19212257, 0.9858362 , 0.56311601, 0.0816607 , 0.52700689,
       0.55360419, 0.44912157, 0.31313867, 0.97764406, 0.47105001,
       0.6513982 , 0.14428815, 0.48821458, 0.90429157, 0.82472026,
       0.49067704, 0.95296257, 0.58335174, 0.99288091, 0.69942103,
       0.17740318, 0.07521884, 0.65462092, 0.59771457, 0.76767736,
       0.33052611, 0.67124601, 0.43317387, 0.40897497, 0.66538164,
       0.51810342, 0.3921522 , 0.39007184, 0.24223748, 0.67974855,
       0.47132882, 0.04886398, 0.29555487, 0.79403151, 0.10849353,
       0.03719661, 0.45388824, 0.90227876, 0.1153054 , 0.13391626,
       0.61895004, 0.68466815, 0.24872544, 0.56075635, 0.93374681,
       0.75485543, 0.46926126, 0.3340845 , 0.30115253, 0.57761135,
       0.05204993, 0.07833301, 0.36477802, 0.53398235, 0.15665

In [96]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
my_data=np.median(data)

In [98]:
my_data

5.0

In [99]:
pip install scipy


In [102]:
from scipy.stats import mode

In [103]:
res=mode(data)

In [104]:
res

ModeResult(mode=1, count=1)

In [3]:
print(np.__version__)
np.show_config()

1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None